title:             Digitale Medizin
email:             info@digitale-medizin.net
# description:       Wahlfachtrack Digitale Meidzin an 
# author:            
baseurl:           "/"
url:               "https://www.digitale-medizin.net"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   digitalemedizin
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
